

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"

  auth_service:
    build: ./auth_service
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/RBAC_SYSTEM
      - JWT_SECRET=itsasecret
      - JWT_EXPIRES_IN=1d
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
  user_service:
    build: ./user_service
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/RBAC_SYSTEM
      - JWT_SECRET=itsasecret
    depends_on:
      - mongo

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_URL: amqp://rabbitmq
  
  role_service:
    build: ./role_service
    container_name: role-permission-service
    ports:
      - '4002:4002'
    environment:
      - MONGO_URI=mongodb://mongo:27017/RBAC_SYSTEM
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - mongo
      - rabbitmq
      

volumes:
  mongo_data:
